stages:
  - build
  - deploy

build_image:
  variables: 
    APP_NAME: web-app
  stage: build
  image: docker
  services:
  - docker:dind
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build -t $CI_COMMIT_SHORT_SHA .
    - docker tag $CI_COMMIT_SHORT_SHA $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}
  only:
    - master
    - develop

deploy_dev:
  stage: deploy
  image: debian:jessie-slim
  variables: 
    APP_NAME: web-app
    APP_INTERNAL_PORT: 3000
    APP_EXTERNAL_PORT: 8050
    CONTAINER_NAME: pebblo.org.web-app.${CI_COMMIT_REF_SLUG}
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AZURE_PROD_SSHKEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    # log into Docker registry
    - ssh pebbloci@$AZURE_PROD_IP "docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
    # Remove image and stop container.
    - ssh pebbloci@$AZURE_PROD_IP "docker rmi $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker stop $CONTAINER_NAME" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker rm $CONTAINER_NAME" || true
    # start new container
    - ssh pebbloci@$AZURE_PROD_IP "docker run --restart unless-stopped --name $CONTAINER_NAME -e NODE_ENV=production -p $APP_EXTERNAL_PORT:$APP_INTERNAL_PORT -d $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}"
  only:
    - develop

deploy:
  stage: deploy
  image: debian:jessie-slim
  variables: 
    APP_NAME: web-app
    APP_INTERNAL_PORT: 3000
    APP_EXTERNAL_PORT: 8001
    CONTAINER_NAME: pebblo.org.web-app.${CI_COMMIT_REF_SLUG}
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AZURE_PROD_SSHKEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    # log into Docker registry
    - ssh pebbloci@$AZURE_PROD_IP "docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
    # Remove image and stop container.
    - ssh pebbloci@$AZURE_PROD_IP "docker rmi $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker stop $CONTAINER_NAME" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker rm $CONTAINER_NAME" || true
    # start new container
    - ssh pebbloci@$AZURE_PROD_IP "docker run --restart unless-stopped --name $CONTAINER_NAME -e NODE_ENV=production -p $APP_EXTERNAL_PORT:$APP_INTERNAL_PORT -d $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:${CI_COMMIT_REF_SLUG}"
  only:
    - master